### ISSUE TITLE
STREAMSCLEQ in ALGOLXEM.alg_m uses wrong comparison operator

### ISSUE THREAD

**Issue by essentialexch** [retro-software/B5500-software#1]
It uses "<" instead of "<=" at sequence number 00883000.

The comment is also wrong at sequence number 00882600.

Thanks.

**Comment by pkimpel** [comment]
Correct. Thanks very much for catching and reporting this. ESPOLXEM had exactly the same problem. Both are now fixed and committed.

**Comment by pkimpel** [comment]
Michael,

Wow, almost 11 years later and a bug like that shows up. Nice catch. 
Thanks for reporting this. I've made the changes, committed them to 
GitHub, and closed the issue.

We never actually used ALGOLXEM and ESPOLXEM. When we started the B5500 
emulator project, we didn't have any software in machine-readable form, 
just scans of listings on bitsavers.org and a few paper listings I had 
squirreled away since 1970. Our only option was to try to transcribe 
those listings and find a way to compile them.

Nigel Williams did the initial transcription of the Mark XVI ALGOL 
compiler and Hans Pufal did one for Mark XVI ESPOL. I proofed the 
transcriptions and then ported them to the modern Unisys ClearPath MCP 
platform, writing all of those stream/character-mode routines in the 
process. The bug you found was certainly mine in cloning STREAMSCLEQ 
from STREAMSCLSS.

After getting those two cross-compilers working, we ended up not using 
them. As I was working on the transcription of the Mark XVI DC-MCP 
listing, Sid McHarg in Seattle, Washington, pulled three B5500 system 
release tapes from the shelf where they had been sitting for 40 years, 
found someone who had what must have been one of the last working 
7-track tape drives on the planet, and somehow managed to read those 
tapes without any errors, giving us a complete B5500 software release 
from late 1971. At that point the XEM compilers were abandoned and 
haven't been used since.

Still, I really appreciate you finding that bug. It made my day today.

Paul Kimpel


------------------------------------------------------------------------

*From:* Michael B. ***@***.***>
*Subject:* [retro-software/B5500-software] STREAMSCLEQ in ALGOLXEM.alg_m 
uses wrong comparison operator (Issue #1)
*Date:* Tuesday, January 10, 2023 at 3:00 PM
*To:* retro-software/B5500-software ***@***.***>
*Cc:* Subscribed ***@***.***>

**Comment by essentialexch** [comment]
Hi Paul -

I spent 19 years of my career working on Burroughs Large Systems, starting on a B6800 in 1980; including five years at Burroughs in Customer Support (first in languages and then in MCP support).

I think you and your team have done an amazing job with the B5500 emulator.

I'd love to extend it for the B6700/B6800/etc. but it seems even less of that software has survived (based on bitsavers). And I can't find any other sources unfortunately. Do you know of any?

So, I thought about writing a Windows compatible compiler for Burroughs ALGOL, just for fun. XALGOL more specifically. And that requires replacing stream procedures.... which led me to your sources.

Thanks for them!

**Comment by essentialexch** [comment]
Actually, I see you might have a scanned printout and the start of a transcription for the 3.3 ALGOL compiler? That would be even better than starting with Mark XVI XALGOL...

**Comment by pkimpel** [comment]
Thanks. The B5500 was my first emulator, and it was quite a challenge, but Nigel and I are very happy with how it turned out.

I don't think extending the B5500 emulator for the B6700 and its successors would be feasible -- the architectures are just too different.

We have some pieces of the Mark II.1 system software source code (ca. 1972) for the B6500 (I don't think the processor upgrade to make it a B6700 was available until 1973). We have sources for MCP, XALGOL compiler, FORTRAN-66 compiler, and several others, but alas, sources for neither the ALGOL nor ESPOL compilers. We also don't have source for the SYSTEM/INTRINSICS (which were a precursor to the GENERALSUPPORT library). Without the compilers we can't compile any of the system software, and without the INTRINSICS we can run user programs under that MCP. So at present we're stuck.

That 3.3 ALGOL compiler is something we started a few years ago in the hopes of eventually being able to back-port it to work on the B6700, but it won't be an easy job. One major problem is that 6-bit character support was dropped in the Bx900 systems (ca. 1980), and as you saw from ALGOLXEM, trying to handle 6-bit character strings on a system with 8-bit characters is messy. The transcription for 3.3 is essentially complete, but the debugging of it was never finished, and the back-porting was never started. Some day we'll probably get back to it.

I'd be happy to send you what II.1 MCP sources we have and the 3.3 ALGOL source in its present state. Please contact me at paul.kimpel@digm.com if you're interested. Since this topic isn't relevant to the B5500, I'd appreciate moving further discussion to email.

**Comment by rcornwell** [comment]
I have MARK XVI XALGOL generated off XV XALGOL via patches if you want to compare.

**Comment by rcornwell** [comment]
I also have a B5500 emulator for SimH. I had some leads on some possible B7900 tapes... but have not heard anything on them.
